vokun:
  image: sonaak/vokun:latest
  env_file: ./postgres.envfile
  command:
  - "-logtostderr"
  - "-v"
  - "2"
  external_links:
  - vokun_postgres
  ports:
  - 9000:9000
  volumes:
  - ./example/:/opt/sonaak/vokun-api/