postgres:
  image: postgres:9.6.2-alpine
  env_file: ./postgres.envfile
  ports:
  - 5432:5432

vokun:
  image: sonaak/vokun:latest
  env_file: ./postgres.envfile
  command:
  - "-logtostderr"
  - "-v"
  - "2"
  ports:
  - 9000:9000
  volumes:
  - ./example/:/opt/sonaak/vokun-api/